spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: document-service
              uri: http://document-service:8081
              predicates:
                - Path=/api/documents/**

            - id: query-service
              uri: http://query-service:8083
              predicates:
                - Path=/api/query/**

            - id: audit-service
              uri: http://audit-service:8084
              predicates:
                - Path=/api/auth/**

            - id: auth-service
              uri: http://document-service:8081
              predicates:
                - Path=/api/auth/**