server:
  port: 8083

spring:
  application:
    name: query-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: document-db
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: query-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

ollama:
  base-url: http://localhost:11434
  embedding-model: nomic-embed-text

chromadb:
  url: http://localhost:8000

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai/v1
  chat-model: llama-3.1-8b-instant

app:
  kafka:
    topic:
      query-executed: query-executed
      doc-embedded: doc-embedded