server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  application:
    name: document-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: document-db

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

aws:
  s3:
    bucket-name: doc-intelligence-anand-2026
    region: ap-south-1

chromadb:
  url: http://localhost:8000

app:
  kafka:
    topic:
      doc-uploaded: doc-uploaded
      doc-deleted: doc-deleted

jwt:
  secret: docintel-secret-key-must-be-at-least-32-characters-long
  expiration: 86400000 # 24 hours in ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html